const galleryActionType={
   galleries:{
    FETCH_GALLERIES_START: "FETCH_GALLERIES_START",
    FETCH_GALLERIES_SUCCESS: "FETCH_GALLERIES_SUCCESS",
    FETCH_GALLERIES_ERROR: "FETCH_GALLERIES_ERROR",
   },
   gallery:{
    FETCH_GALLERY_START: "FETCH_GALLERY_START",
    FETCH_GALLERY_SUCCESS: "FETCH_GALLERY_SUCCESS",
    FETCH_GALLERY_ERROR: "FETCH_GALLERY_ERROR",
   },
}

export default galleryActionType